[package]
name = "go_harness"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
protocol = { path = "../protocol" }
tree-sitter = { workspace = true }
tree-sitter-go = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
