[package]
name = "scip_mapper"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
protocol = { path = "../protocol" }
anyhow = { workspace = true }
protobuf = "3.7"
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }