[package]
name = "csharp_harness"
version = "0.1.0"
edition = "2021"

[dependencies]
tree-sitter = "0.20"
tree-sitter-c-sharp = "0.20"
protocol = { path = "../protocol" }
anyhow = "1.0"
serde_json = "1.0"

[dev-dependencies]
tempfile = "3.8"